//mimetypes for sorting files
const types = {
  "audio/mpeg": "audio",
  "audio/wav": "audio",
  "audio/aac": "audio",
  "audio/ogg": "audio",
  "audio/opus": "audio",
  "audio/wav": "audio",
  "audio/webm": "audio",
  "audio/aac": "audio",
  "audio/midi": "audio",
  "audio/x-midi": "audio",
  "video/x-msvideo":"video",
  "video/mp4":"video",
  "video/mpeg":"video",
  "video/ogg":"video",
  "video/mp2t":"video",
  "video/webm":"video",
  "video/3gpp":"video",
  "video/3gpp2":"video",
  "image/avif":"image",
  "image/bmp":"image",
  "image/gif":"image",
  "image/vnd.microsoft.icon":"image",
  "image/jpeg":"image",
  "image/png":"image",
  "image/svg+xml":"image",
  "image/tiff":"image",
  "image/webp":"image",
  "application/pdf":"document",
  "application/pdf":"document",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation":"document",
  "other": "other_type",
};
